#!/usr/bin/env bash
# =============================================================================
# 09-pgbouncer-setup.sh — Install and configure PgBouncer on an Odoo app node
# Run on EACH Odoo app node.
# Usage: sudo bash 09-pgbouncer-setup.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
load_env

LOG_FILE="/tmp/cluster-setup-09-pgbouncer.log"
require_root
require_ubuntu

log_section "09 — PgBouncer Setup on $(hostname)"

# ── Install PgBouncer ─────────────────────────────────────────────────────────
log_step "Installing PgBouncer..."
apt_update
apt_install pgbouncer

# ── Create dirs and set ownership ────────────────────────────────────────────
mkdir -p /var/log/pgbouncer /var/run/pgbouncer
chown pgbouncer:pgbouncer /var/log/pgbouncer /var/run/pgbouncer

# ── Write pgbouncer.ini ───────────────────────────────────────────────────────
log_step "Writing PgBouncer configuration..."
backup_file /etc/pgbouncer/pgbouncer.ini

cat > /etc/pgbouncer/pgbouncer.ini <<EOF
; ============================================================
; PgBouncer Configuration
; Generated by 09-pgbouncer-setup.sh on $(date)
; Node: $(hostname)
; ============================================================

[databases]
; Route default DB to YugabyteDB cluster
; Round-robin across all 3 nodes (PgBouncer picks first available)
${DB_ODOO_NAME} = host=${YB_NODE1_HOST} port=${YB_YSQL_PORT} dbname=${DB_ODOO_NAME}
${DB_ODOO_NAME}_yb2 = host=${YB_NODE2_HOST} port=${YB_YSQL_PORT} dbname=${DB_ODOO_NAME}
${DB_ODOO_NAME}_yb3 = host=${YB_NODE3_HOST} port=${YB_YSQL_PORT} dbname=${DB_ODOO_NAME}

; Wildcard fallback
* = host=${YB_NODE1_HOST} port=${YB_YSQL_PORT}

[pgbouncer]
; ── Network ────────────────────────────────────────────────
listen_addr = ${PGBOUNCER_HOST}
listen_port = ${PGBOUNCER_PORT}
unix_socket_dir = /var/run/pgbouncer
unix_socket_mode = 0777

; ── Auth ───────────────────────────────────────────────────
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

; ── Pool ───────────────────────────────────────────────────
pool_mode = ${PGBOUNCER_POOL_MODE}
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}
min_pool_size = 5
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE}
reserve_pool_timeout = 3
max_db_connections = 100
max_user_connections = 0

; ── Server Checks ──────────────────────────────────────────
server_reset_query = DISCARD ALL
server_check_query = SELECT 1
server_check_delay = 30
server_idle_timeout = 600
client_idle_timeout = 600
server_lifetime = 3600

; ── Logging ────────────────────────────────────────────────
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
stats_period = 60

; ── Compatibility ──────────────────────────────────────────
ignore_startup_parameters = extra_float_digits,search_path

; ── Admin ──────────────────────────────────────────────────
admin_users = pgbouncer_admin
stats_users = pgbouncer_stats

EOF

log_ok "PgBouncer config written"

# ── Write userlist ────────────────────────────────────────────────────────────
log_step "Writing PgBouncer userlist..."
# PgBouncer requires MD5 hash: "md5" + md5(password + username)
ODOO_MD5_HASH="md5$(printf '%s' "${DB_ODOO_PASS}${DB_ODOO_USER}" | md5sum | awk '{print $1}')"

cat > /etc/pgbouncer/userlist.txt <<EOF
"${DB_ODOO_USER}" "${ODOO_MD5_HASH}"
"pgbouncer_admin" "md5$(printf '%s%s' 'pgbouncer_admin_pass' 'pgbouncer_admin' | md5sum | awk '{print $1}')"
"pgbouncer_stats" "md5$(printf '%s%s' 'pgbouncer_stats_pass' 'pgbouncer_stats' | md5sum | awk '{print $1}')"
EOF

chmod 640 /etc/pgbouncer/userlist.txt
chown pgbouncer:pgbouncer /etc/pgbouncer/userlist.txt /etc/pgbouncer/pgbouncer.ini
log_ok "Userlist configured"

# ── Enable PgBouncer ──────────────────────────────────────────────────────────
log_step "Enabling PgBouncer service..."
service_enable_start pgbouncer

# ── Verify ────────────────────────────────────────────────────────────────────
log_step "Verifying PgBouncer connection..."
sleep 2

# Test connection through PgBouncer
PGPASSWORD="${DB_ODOO_PASS}" psql \
    -h "${PGBOUNCER_HOST}" \
    -p "${PGBOUNCER_PORT}" \
    -U "${DB_ODOO_USER}" \
    -d "${DB_ODOO_NAME}" \
    -c "SELECT current_database(), current_user;" >> "$LOG_FILE" 2>&1 \
    && log_ok "PgBouncer → YugabyteDB connection successful" \
    || log_warn "PgBouncer connection test failed — verify YugabyteDB is reachable"

# Check PgBouncer stats
PGPASSWORD="pgbouncer_admin_pass" psql \
    -h "${PGBOUNCER_HOST}" \
    -p "${PGBOUNCER_PORT}" \
    -U pgbouncer_admin \
    -d pgbouncer \
    -c "SHOW POOLS;" >> "$LOG_FILE" 2>&1 || true

log_ok "PgBouncer setup verified"

print_summary "PgBouncer Ready on $(hostname)" \
    "Listen:       ${PGBOUNCER_HOST}:${PGBOUNCER_PORT}" \
    "Pool mode:    ${PGBOUNCER_POOL_MODE}" \
    "Max clients:  ${PGBOUNCER_MAX_CLIENT_CONN}" \
    "Pool size:    ${PGBOUNCER_DEFAULT_POOL_SIZE}" \
    "Backend:      ${YB_NODE1_HOST}:${YB_YSQL_PORT} (YugabyteDB)" \
    "Next step:    Run 10-haproxy-setup.sh on haproxy nodes" \
    "Log file:     ${LOG_FILE}"
