#!/usr/bin/env bash
# =============================================================================
# 10-haproxy-setup.sh — Install HAProxy + Keepalived for load balancing
# Run on haproxy-01 AND haproxy-02.
# The script auto-detects MASTER vs BACKUP role based on IP.
# Usage: sudo bash 10-haproxy-setup.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
load_env

LOG_FILE="/tmp/cluster-setup-10-haproxy.log"
require_root
require_ubuntu

NODE_IP=$(hostname -I | awk '{print $1}')
log_section "10 — HAProxy + Keepalived Setup on $(hostname) (${NODE_IP})"

# ── Determine role ────────────────────────────────────────────────────────────
if [[ "$NODE_IP" == "$LB_PRIMARY_IP" ]]; then
    KEEPALIVED_STATE="MASTER"
    KEEPALIVED_PRIORITY="200"
    log_info "Role: MASTER load balancer (${LB_PRIMARY_HOST})"
elif [[ "$NODE_IP" == "$LB_BACKUP_IP" ]]; then
    KEEPALIVED_STATE="BACKUP"
    KEEPALIVED_PRIORITY="100"
    log_info "Role: BACKUP load balancer (${LB_BACKUP_HOST})"
else
    die "Node IP ${NODE_IP} is not in the load balancer list. Check .env settings."
fi

# ── Install packages ──────────────────────────────────────────────────────────
log_step "Installing HAProxy and Keepalived..."
apt_update
apt_install haproxy keepalived

# ── SSL Certificate ───────────────────────────────────────────────────────────
log_step "Configuring SSL certificate..."
mkdir -p "${SSL_DIR}"

if [[ ! -f "${SSL_DIR}/odoo.pem" ]]; then
    log_info "Generating self-signed certificate for ${SSL_CN}..."
    openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
        -keyout "${SSL_DIR}/odoo.key" \
        -out "${SSL_DIR}/odoo.crt" \
        -subj "/C=${SSL_COUNTRY}/ST=${SSL_STATE}/O=${SSL_ORG}/CN=${SSL_CN}" \
        >> "$LOG_FILE" 2>&1

    # HAProxy needs key + cert in a single PEM file
    cat "${SSL_DIR}/odoo.crt" "${SSL_DIR}/odoo.key" > "${SSL_DIR}/odoo.pem"
    chmod 600 "${SSL_DIR}/odoo.pem" "${SSL_DIR}/odoo.key"
    log_ok "Self-signed certificate generated"
else
    log_info "Certificate already exists: ${SSL_DIR}/odoo.pem"
fi

# ── HAProxy Configuration ─────────────────────────────────────────────────────
log_step "Writing HAProxy configuration..."
backup_file /etc/haproxy/haproxy.cfg

cat > /etc/haproxy/haproxy.cfg <<EOF
# ============================================================
# HAProxy Configuration — Odoo ${ODOO_VERSION} Cluster
# Generated by 10-haproxy-setup.sh on $(date)
# Node: $(hostname) | Role: ${KEEPALIVED_STATE}
# ============================================================

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    maxconn 50000
    tune.ssl.default-dh-param 2048
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-sslv3 no-tlsv10 no-tlsv11
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  forwardfor
    option  http-server-close
    option  redispatch
    retries 3
    timeout connect 5s
    timeout client  60s
    timeout server  60s
    timeout check   5s
    timeout tunnel  3600s
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 503 /etc/haproxy/errors/503.http

# ── Stats Dashboard ──────────────────────────────────────────────────────────
listen stats
    bind *:${LB_STATS_PORT}
    stats enable
    stats uri /stats
    stats refresh 10s
    stats auth ${LB_STATS_USER}:${LB_STATS_PASS}
    stats show-legends
    stats show-node
    stats hide-version

# ── HTTP Redirect ─────────────────────────────────────────────────────────────
frontend http_redirect
    bind *:80
    http-request redirect scheme https unless { ssl_fc }

# ── HTTPS Frontend ────────────────────────────────────────────────────────────
frontend odoo_https_front
    bind *:443 ssl crt ${SSL_DIR}/odoo.pem alpn h2,http/1.1
    http-request set-header X-Forwarded-Proto https
    http-request set-header X-Forwarded-Port 443
    http-request set-header X-Real-IP %[src]
    http-request add-header X-Forwarded-For %[src]

    # Security headers
    http-response set-header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
    http-response set-header X-Content-Type-Options "nosniff"
    http-response set-header X-Frame-Options "SAMEORIGIN"
    http-response set-header X-XSS-Protection "1; mode=block"
    http-response set-header Referrer-Policy "strict-origin-when-cross-origin"

    # Connection rate limit (50 per IP per 10s)
    stick-table type ip size 100k expire 10s store conn_rate(10s)
    http-request track-sc0 src
    http-request deny deny_status 429 if { sc_conn_rate(0) gt 50 }

    # Route longpolling to dedicated backend
    acl is_longpoll path_beg /longpolling
    acl is_websocket hdr(Upgrade) -i websocket
    use_backend odoo_longpoll if is_longpoll or is_websocket

    default_backend odoo_web

# ── Odoo Web Backend ──────────────────────────────────────────────────────────
backend odoo_web
    balance leastconn
    option httpchk GET /web/health HTTP/1.1\r\nHost:\ localhost
    http-check expect status 200

    # Cookie-based sticky sessions (fallback safety)
    cookie SERVERID insert indirect nocache httponly secure

    server ${ODOO_NODE1_HOST} ${ODOO_NODE1_IP}:${ODOO_HTTP_PORT} \\
        check inter 3s rise 2 fall 3 \\
        cookie ${ODOO_NODE1_HOST} \\
        maxconn 500 \\
        weight 100

    server ${ODOO_NODE2_HOST} ${ODOO_NODE2_IP}:${ODOO_HTTP_PORT} \\
        check inter 3s rise 2 fall 3 \\
        cookie ${ODOO_NODE2_HOST} \\
        maxconn 500 \\
        weight 100

# ── Odoo Longpolling Backend ──────────────────────────────────────────────────
backend odoo_longpoll
    balance source
    option httpchk GET /web/health HTTP/1.1\r\nHost:\ localhost
    http-check expect status 200
    timeout tunnel 3600s

    server ${ODOO_NODE1_HOST}_lp ${ODOO_NODE1_IP}:${ODOO_LONGPOLL_PORT} \\
        check inter 5s rise 2 fall 3 \\
        maxconn 200

    server ${ODOO_NODE2_HOST}_lp ${ODOO_NODE2_IP}:${ODOO_LONGPOLL_PORT} \\
        check inter 5s rise 2 fall 3 \\
        maxconn 200

EOF

# ── Validate HAProxy config ────────────────────────────────────────────────────
log_step "Validating HAProxy configuration..."
haproxy -c -f /etc/haproxy/haproxy.cfg >> "$LOG_FILE" 2>&1 \
    && log_ok "HAProxy config is valid" \
    || die "HAProxy config validation failed. Check ${LOG_FILE}"

# ── Enable HAProxy ────────────────────────────────────────────────────────────
service_enable_start haproxy

# ── Keepalived Configuration ──────────────────────────────────────────────────
log_step "Writing Keepalived configuration (${KEEPALIVED_STATE})..."
backup_file /etc/keepalived/keepalived.conf

cat > /etc/keepalived/keepalived.conf <<EOF
! ============================================================
! Keepalived Configuration — Odoo Cluster
! Generated by 10-haproxy-setup.sh on $(date)
! Node: $(hostname) | Role: ${KEEPALIVED_STATE}
! ============================================================

global_defs {
    notification_email {
        ${ALERT_EMAIL}
    }
    notification_email_from keepalived@$(hostname)
    smtp_server 127.0.0.1
    smtp_connect_timeout 30
    router_id $(hostname | tr '[:lower:]-' '[:upper:]_')
    vrrp_garp_interval 0
    vrrp_gna_interval 0
    script_user root
    enable_script_security
}

vrrp_script check_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval 2
    weight 2
    fall 2
    rise 1
}

vrrp_instance VI_ODOO {
    state ${KEEPALIVED_STATE}
    interface ${VIP_INTERFACE}
    virtual_router_id ${VIP_ROUTER_ID}
    priority ${KEEPALIVED_PRIORITY}
    advert_int 1
    preempt_delay 5
    authentication {
        auth_type PASS
        auth_pass ${VIP_AUTH_PASS}
    }
    virtual_ipaddress {
        ${VIP_IP}/${VIP_CIDR} dev ${VIP_INTERFACE} label ${VIP_INTERFACE}:vip
    }
    track_script {
        check_haproxy
    }
    notify_master   "/etc/keepalived/notify.sh MASTER"
    notify_backup   "/etc/keepalived/notify.sh BACKUP"
    notify_fault    "/etc/keepalived/notify.sh FAULT"
}
EOF

# ── Keepalived notify script ──────────────────────────────────────────────────
cat > /etc/keepalived/notify.sh <<'EOF'
#!/bin/bash
STATE="$1"
DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "${DATE} Keepalived transitioned to: ${STATE}" >> /var/log/keepalived-notify.log
# Add email/webhook notification here if needed
EOF
chmod +x /etc/keepalived/notify.sh

# ── Enable Keepalived ─────────────────────────────────────────────────────────
service_enable_start keepalived

# ── UFW rules for load balancer ───────────────────────────────────────────────
log_step "Configuring firewall for load balancer..."
ufw allow 80/tcp    comment "HTTP redirect" >> "$LOG_FILE" 2>&1
ufw allow 443/tcp   comment "HTTPS" >> "$LOG_FILE" 2>&1
ufw allow "${LB_STATS_PORT}/tcp" comment "HAProxy stats" >> "$LOG_FILE" 2>&1
# Keepalived VRRP
ufw allow proto vrrp from "${LB_PRIMARY_IP}" comment "Keepalived VRRP" >> "$LOG_FILE" 2>&1
ufw allow proto vrrp from "${LB_BACKUP_IP}"  comment "Keepalived VRRP" >> "$LOG_FILE" 2>&1
log_ok "Firewall rules applied"

# ── Verify ────────────────────────────────────────────────────────────────────
log_step "Checking HAProxy backend status..."
sleep 3
echo "show stat" | socat stdio /run/haproxy/admin.sock 2>/dev/null \
    | awk -F, 'NR==1 || $2~/odoo/' \
    | column -t -s, 2>/dev/null \
    | head -20 \
    || log_warn "Could not query HAProxy stats socket (may take a moment)"

log_step "Checking VIP assignment..."
ip addr show "${VIP_INTERFACE}" | grep -q "${VIP_IP}" \
    && log_ok "VIP ${VIP_IP} is assigned to this node" \
    || log_info "VIP ${VIP_IP} is on the other node (normal for BACKUP)"

print_summary "HAProxy + Keepalived Ready on $(hostname)" \
    "Role:         ${KEEPALIVED_STATE} (priority ${KEEPALIVED_PRIORITY})" \
    "VIP:          ${VIP_IP}" \
    "HTTP:         port 80 → redirect to HTTPS" \
    "HTTPS:        port 443 → Odoo backends" \
    "Stats UI:     http://$(hostname):${LB_STATS_PORT}/stats" \
    "Next step:    Run 11-odoo-service.sh on each Odoo app node" \
    "Log file:     ${LOG_FILE}"
