#!/usr/bin/env bash
# =============================================================================
# 11-odoo-service.sh — Configure Odoo systemd service and (first-node) DB init
# Run on EACH Odoo app node. DB init only runs from the primary node.
# Usage: sudo bash 11-odoo-service.sh [--init-db]
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
load_env

LOG_FILE="/tmp/cluster-setup-11-odoo-service.log"
require_root

INIT_DB=false
[[ "${1:-}" == "--init-db" ]] && INIT_DB=true

NODE_IP=$(hostname -I | awk '{print $1}')
log_section "11 — Odoo Service Setup on $(hostname) (${NODE_IP})"

# ── Verify prerequisites ──────────────────────────────────────────────────────
log_step "Checking prerequisites..."
[[ -f "${ODOO_CONFIG_FILE}" ]]            || die "Odoo config not found. Run 08-odoo-install.sh first."
[[ -d "${ODOO_SOURCE_DIR}" ]]             || die "Odoo source not found. Run 08-odoo-install.sh first."
[[ -x "${ODOO_VENV_DIR}/bin/python3" ]]   || die "Python venv not found. Run 08-odoo-install.sh first."
mountpoint -q "${NFS_MOUNT_PATH}"         || die "NFS not mounted. Run 06-nfs-client.sh first."
log_ok "Prerequisites satisfied"

# ── Test PgBouncer connectivity ───────────────────────────────────────────────
log_step "Verifying database connectivity through PgBouncer..."
PGPASSWORD="${DB_ODOO_PASS}" psql \
    -h "${PGBOUNCER_HOST}" \
    -p "${PGBOUNCER_PORT}" \
    -U "${DB_ODOO_USER}" \
    -d "${DB_ODOO_NAME}" \
    -c "SELECT 1 AS db_ok;" >> "$LOG_FILE" 2>&1 \
    && log_ok "Database reachable via PgBouncer" \
    || die "Cannot reach database. Check PgBouncer and YugabyteDB."

# ── Test Redis connectivity ───────────────────────────────────────────────────
log_step "Verifying Redis connectivity..."
redis-cli -h "${REDIS_HOST}" -p "${REDIS_PORT}" -a "${REDIS_PASS}" ping >> "$LOG_FILE" 2>/dev/null \
    && log_ok "Redis reachable" \
    || log_warn "Redis not reachable — sessions may not persist across restarts"

# ── Database Initialization (first node only, or when --init-db is passed) ────
if $INIT_DB || [[ "$NODE_IP" == "$ODOO_NODE1_IP" ]]; then
    # Check if DB is already initialized
    TABLE_COUNT=$(PGPASSWORD="${DB_ODOO_PASS}" psql \
        -h "${PGBOUNCER_HOST}" \
        -p "${PGBOUNCER_PORT}" \
        -U "${DB_ODOO_USER}" \
        -d "${DB_ODOO_NAME}" \
        -tAc "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';" \
        2>/dev/null || echo "0")

    if [[ "${TABLE_COUNT:-0}" -gt 10 ]]; then
        log_info "Database already initialized (${TABLE_COUNT} tables found) — skipping init"
    else
        log_section "Initializing Odoo Database (first run)"
        log_info "This may take 5-10 minutes..."

        sudo -u "${ODOO_USER}" "${ODOO_VENV_DIR}/bin/python3" \
            "${ODOO_SOURCE_DIR}/odoo-bin" \
            --config="${ODOO_CONFIG_FILE}" \
            --init=base \
            --stop-after-init \
            --log-level=info \
            --logfile="${ODOO_LOG_DIR}/odoo-init.log" \
            2>&1 | tee -a "$LOG_FILE"

        INIT_EXIT=${PIPESTATUS[0]}
        if [[ $INIT_EXIT -ne 0 ]]; then
            log_error "Database init failed with exit code ${INIT_EXIT}"
            log_error "Check ${ODOO_LOG_DIR}/odoo-init.log for details"
            die "DB initialization failed"
        fi

        # Verify
        TABLE_COUNT_AFTER=$(PGPASSWORD="${DB_ODOO_PASS}" psql \
            -h "${PGBOUNCER_HOST}" \
            -p "${PGBOUNCER_PORT}" \
            -U "${DB_ODOO_USER}" \
            -d "${DB_ODOO_NAME}" \
            -tAc "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';" \
            2>/dev/null || echo "0")
        log_ok "Database initialized: ${TABLE_COUNT_AFTER} tables created"
    fi
fi

# ── Create systemd service ────────────────────────────────────────────────────
log_step "Creating Odoo systemd service..."
cat > /etc/systemd/system/odoo19.service <<EOF
# ============================================================
# Odoo 19 systemd service
# Generated by 11-odoo-service.sh on $(date)
# Node: $(hostname)
# ============================================================
[Unit]
Description=Odoo 19 Application Server
Documentation=https://www.odoo.com/documentation/19.0
After=network.target remote-fs.target
Wants=network.target remote-fs.target

[Service]
Type=simple
User=${ODOO_USER}
Group=${ODOO_GROUP}
SyslogIdentifier=odoo19

ExecStart=${ODOO_VENV_DIR}/bin/python3 ${ODOO_SOURCE_DIR}/odoo-bin \\
    --config=${ODOO_CONFIG_FILE} \\
    --logfile=${ODOO_LOG_DIR}/odoo.log

ExecReload=/bin/kill -HUP \$MAINPID

Restart=on-failure
RestartSec=5
KillMode=mixed
TimeoutStopSec=60

; Resource limits
LimitNOFILE=65536
LimitNPROC=4096
PrivateTmp=true
NoNewPrivileges=true
ProtectSystem=full

; Environment
Environment="PYTHONPATH=${ODOO_SOURCE_DIR}"
Environment="ODOO_RC=${ODOO_CONFIG_FILE}"

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
log_ok "Systemd service created: odoo19.service"

# ── Enable and Start Odoo ─────────────────────────────────────────────────────
log_step "Enabling and starting Odoo service..."
service_enable_start odoo19

# ── Wait for Odoo to be ready ─────────────────────────────────────────────────
log_step "Waiting for Odoo HTTP to be ready (up to 120s)..."
for i in $(seq 1 40); do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
        "http://127.0.0.1:${ODOO_HTTP_PORT}/web/health" 2>/dev/null || echo "0")
    if [[ "$HTTP_CODE" == "200" ]]; then
        log_ok "Odoo is responding (HTTP 200)"
        break
    fi
    echo -n "." && sleep 3
done

if [[ "$HTTP_CODE" != "200" ]]; then
    log_warn "Odoo did not respond with HTTP 200 in time (got: ${HTTP_CODE})"
    log_warn "Check: journalctl -u odoo19 -f"
else
    # Quick sanity check on the health endpoint
    HEALTH=$(curl -s "http://127.0.0.1:${ODOO_HTTP_PORT}/web/health" 2>/dev/null)
    log_ok "Health endpoint: ${HEALTH}"
fi

# ── Cron worker validation ────────────────────────────────────────────────────
log_step "Checking worker processes..."
sleep 5
WORKER_COUNT=$(pgrep -u "${ODOO_USER}" -c python3 2>/dev/null || echo "0")
log_info "Active Odoo worker processes: ${WORKER_COUNT}"

print_summary "Odoo 19 Service Running on $(hostname)" \
    "Service:    odoo19.service (systemd)" \
    "HTTP:       http://$(hostname):${ODOO_HTTP_PORT}" \
    "Longpoll:  http://$(hostname):${ODOO_LONGPOLL_PORT}" \
    "Workers:   ${ODOO_WORKERS} (+ ${ODOO_MAX_CRON_THREADS} cron)" \
    "Log:       ${ODOO_LOG_DIR}/odoo.log" \
    "Next step: Run 12-health-check.sh to verify the full cluster" \
    "Log file:  ${LOG_FILE}"
